name: build-all

on:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash
    working-directory: test/

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y libzip-dev
    - run: CC=gcc make -B
    - run: CC=clang make -B

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgArguments: 'libzip'

    - run: make -B
      env:
        CC: gcc
    - run: make -B
      env:
        CC: clang
